import { existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Build the Omniverse garden the visualizer renders from the catalog SSOT.
 *
 * Reads `_meta/catalog.json` (emitted by omni-api `bun catalog:export`) and
 * maps it onto the garden schema: realms -> subgardens, products -> sprouts,
 * and the connection graph -> typed cross-sprout `edges`. Writes a committed
 * `src/lib/garden/garden.generated.ts`. Never hand-edit that file.
 */

const catalogPath = resolve(import.meta.dir, "../../../_meta/catalog.json");
const outPath = resolve(import.meta.dir, "../lib/garden/garden.generated.ts");

if (!existsSync(catalogPath)) {
	// biome-ignore lint/suspicious/noConsole: build script output
	console.warn(
		`[garden] ${catalogPath} not found, keeping the committed garden.generated.ts`,
	);
	process.exit(0);
}

type Product = {
	id: string;
	name: string;
	icon?: string;
	realm?: string | null;
	description?: string;
	tagline?: string;
	websiteUrl?: string;
	docsUrl?: string;
	license?: string;
	selfHostable?: boolean;
	isPublic?: boolean;
	/** ISO release date. Absent means the product has not launched yet. */
	releaseDate?: string;
};
type Realm = {
	slug: string;
	name: string;
	icon?: string;
	description?: string;
	tagline?: string;
};
type Connection = {
	source: string | string[];
	target: string | string[];
	relations?: string[];
	description?: string;
	status?: string;
};
type Catalog = {
	realms: Realm[];
	products: Product[];
	connections: Connection[];
};

const catalog = (await Bun.file(catalogPath).json()) as Catalog;

// Only launched products are shown. `releaseDate` is the catalog's launch
// signal, so a product without one is still in flight and hidden until it
// ships (its typed connections drop out with it).
const launchedProducts = catalog.products.filter((p) => Boolean(p.releaseDate));

const productsById = new Map(launchedProducts.map((p) => [p.id, p]));
const asArray = (v: string | string[]): string[] =>
	Array.isArray(v) ? v : [v];

// Docs URLs in the catalog are paths on the central docs site (e.g.
// `/core/runa`); absolute URLs pass through untouched.
const DOCS_BASE = "https://docs.omni.dev";
const resolveDocsUrl = (docsUrl?: string): string => {
	if (!docsUrl) return "";
	return /^https?:\/\//.test(docsUrl) ? docsUrl : `${DOCS_BASE}${docsUrl}`;
};

const sprout = (p: Product) => ({
	name: p.name,
	homepage_url: p.websiteUrl ?? "",
	description: p.description ?? "",
	logo: p.icon ?? "",
	tagline: p.tagline ?? "",
	license: p.license ?? "",
	release_date: p.releaseDate ?? "",
	self_hostable: p.selfHostable ?? false,
	docs_url: resolveDocsUrl(p.docsUrl),
});

// realms -> subgardens (each carries its products as sprouts). Realms with no
// launched products are dropped so the garden never shows an empty branch.
const subgardens = catalog.realms
	.map((realm) => ({
		name: realm.name,
		description: realm.tagline
			? `${realm.tagline} - ${realm.description ?? ""}`.trim()
			: (realm.description ?? ""),
		icon: realm.icon,
		supergardens: [{ name: "Omniverse" }],
		sprouts: launchedProducts.filter((p) => p.realm === realm.slug).map(sprout),
	}))
	.filter((subgarden) => subgarden.sprouts.length > 0);

// realm-less products (Orin, Launcher, ...) grouped so they aren't lost
const orphanProducts = launchedProducts.filter((p) => !p.realm);
if (orphanProducts.length) {
	subgardens.push({
		name: "META",
		description: "Cross-realm products that span the whole ecosystem",
		icon: "🌐",
		supergardens: [{ name: "Omniverse" }],
		sprouts: orphanProducts.map(sprout),
	});
}

// connection graph -> typed cross-sprout edges (endpoints matched by name)
const edges: Array<{
	source: string;
	target: string;
	relations: string[];
	description?: string;
	status?: string;
}> = [];
for (const conn of catalog.connections) {
	for (const src of asArray(conn.source)) {
		for (const tgt of asArray(conn.target)) {
			const sourceName = productsById.get(src)?.name;
			const targetName = productsById.get(tgt)?.name;
			if (!sourceName || !targetName || sourceName === targetName) continue;
			edges.push({
				source: sourceName,
				target: targetName,
				relations: conn.relations ?? [],
				description: conn.description,
				status: conn.status,
			});
		}
	}
}

const garden = {
	name: "Omniverse",
	description: "The complete Omni product ecosystem",
	icon: "🌱",
	subgardens,
	edges,
};

const file = `/**
 * Omniverse garden, generated from the catalog SSOT (\`_meta/catalog.json\`).
 *
 * AUTO-GENERATED by src/scripts/generateGarden.ts. Do not edit by hand.
 * Refresh with \`bun run src/scripts/generateGarden.ts\` from the metarepo.
 */

import type { GardenSchema } from "@omnidotdev/garden";

export const omniGarden = ${JSON.stringify(garden, null, 2)} as GardenSchema;
`;

await Bun.write(outPath, file);

// biome-ignore lint/suspicious/noConsole: build script output
console.info(
	`[garden] Wrote ${subgardens.length} realms, ${launchedProducts.length} products, ${edges.length} edges`,
);
