import { resolve } from "node:path";

import { buildGarden, CATALOG_QUERY } from "../lib/garden/buildGarden";

import type { CatalogData } from "../lib/garden/buildGarden";

/**
 * Build the committed Omniverse garden snapshot from the catalog SSOT.
 *
 * Pulls the public catalog from omni-api's GraphQL (the catalog is DB-synced
 * there and filtered to `is_public` server-side) and runs the shared
 * `buildGarden` transform (see `src/lib/garden/buildGarden.ts`), the same one
 * the runtime fetch uses, so the snapshot and the live garden can never drift.
 *
 * The result is cached to the committed `src/lib/garden/garden.generated.ts`.
 * This snapshot is the OFFLINE FALLBACK: at runtime the app fetches the live
 * catalog and only falls back to this file if that fetch fails, and a build
 * without egress (CI, or an omni-api outage) keeps the last good snapshot.
 * Never hand-edit the generated file.
 */

const GRAPHQL_URL =
	process.env.OMNI_API_GRAPHQL_URL ?? "https://api.omni.dev/graphql";
const outPath = resolve(import.meta.dir, "../lib/garden/garden.generated.ts");

type GqlResponse = { errors?: unknown; data?: CatalogData };

let payload: GqlResponse | undefined;
try {
	const res = await fetch(GRAPHQL_URL, {
		method: "POST",
		headers: { "content-type": "application/json" },
		body: JSON.stringify({ query: CATALOG_QUERY }),
	});
	if (res.ok) {
		payload = (await res.json()) as GqlResponse;
	} else {
		// biome-ignore lint/suspicious/noConsole: build script output
		console.warn(`[garden] omni-api ${GRAPHQL_URL} returned ${res.status}`);
	}
} catch (error) {
	// biome-ignore lint/suspicious/noConsole: build script output
	console.warn(
		`[garden] could not reach omni-api at ${GRAPHQL_URL} (${error})`,
	);
}

// Fall back to the committed cache when omni-api is unreachable or empty, so a
// build without egress (or during an outage) still ships the last good garden.
const data = payload?.data;
if (payload?.errors || !data) {
	// biome-ignore lint/suspicious/noConsole: build script output
	console.warn(
		"[garden] no usable catalog from omni-api; keeping committed garden.generated.ts",
	);
	process.exit(0);
}

const garden = buildGarden(data);

const file = `/**
 * Omniverse garden snapshot, generated from the catalog SSOT (omni-api GraphQL).
 *
 * AUTO-GENERATED by src/scripts/generateGarden.ts. Do not edit by hand.
 * Refresh with \`bun run src/scripts/generateGarden.ts\`.
 *
 * This is the OFFLINE FALLBACK only; at runtime the app fetches the live
 * catalog (see src/lib/garden/useGarden.ts) and uses this snapshot if that
 * fetch fails.
 */

import type { GardenSchema } from "@omnidotdev/garden";

export const omniGarden = ${JSON.stringify(garden, null, 2)} as GardenSchema;
`;

await Bun.write(outPath, file);

const subgardens = garden.subgardens ?? [];
const sprouts = subgardens.flatMap((s) => s.sprouts ?? []);
// biome-ignore lint/suspicious/noConsole: build script output
console.info(
	`[garden] Wrote ${subgardens.length} realms, ${sprouts.length} products (${sprouts.filter((s) => s.coming_soon).length} coming soon), ${garden.edges?.length ?? 0} edges`,
);
