import { existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Build the Omniverse garden the visualizer renders from the catalog SSOT.
 *
 * Reads `_meta/catalog.json` (emitted by omni-api `bun catalog:export`) and
 * maps it onto the garden schema: realms -> subgardens, products -> sprouts,
 * and the connection graph -> typed cross-sprout `edges`. Writes a committed
 * `src/lib/garden/garden.generated.ts`. Never hand-edit that file.
 */

const catalogPath = resolve(import.meta.dir, "../../../_meta/catalog.json");
const outPath = resolve(import.meta.dir, "../lib/garden/garden.generated.ts");

if (!existsSync(catalogPath)) {
	// biome-ignore lint/suspicious/noConsole: build script output
	console.warn(
		`[garden] ${catalogPath} not found, keeping the committed garden.generated.ts`,
	);
	process.exit(0);
}

type Product = {
	id: string;
	name: string;
	icon?: string;
	realm?: string | null;
	description?: string;
	websiteUrl?: string;
	docsUrl?: string;
};
type Realm = {
	slug: string;
	name: string;
	icon?: string;
	description?: string;
	tagline?: string;
};
type Connection = {
	source: string | string[];
	target: string | string[];
	relations?: string[];
	description?: string;
	status?: string;
};
type Catalog = {
	realms: Realm[];
	products: Product[];
	connections: Connection[];
};

const catalog = (await Bun.file(catalogPath).json()) as Catalog;

const productsById = new Map(catalog.products.map((p) => [p.id, p]));
const asArray = (v: string | string[]): string[] =>
	Array.isArray(v) ? v : [v];

const sprout = (p: Product) => ({
	name: p.name,
	homepage_url: p.websiteUrl ?? "",
	description: p.description ?? "",
	logo: p.icon ?? "",
});

// realms -> subgardens (each carries its products as sprouts)
const subgardens = catalog.realms.map((realm) => ({
	name: realm.name,
	description: realm.tagline
		? `${realm.tagline} - ${realm.description ?? ""}`.trim()
		: (realm.description ?? ""),
	icon: realm.icon,
	supergardens: [{ name: "Omniverse" }],
	sprouts: catalog.products.filter((p) => p.realm === realm.slug).map(sprout),
}));

// realm-less products (Orin, Launcher, ...) grouped so they aren't lost
const orphanProducts = catalog.products.filter((p) => !p.realm);
if (orphanProducts.length) {
	subgardens.push({
		name: "META",
		description: "Cross-realm products that span the whole ecosystem",
		icon: "🌐",
		supergardens: [{ name: "Omniverse" }],
		sprouts: orphanProducts.map(sprout),
	});
}

// connection graph -> typed cross-sprout edges (endpoints matched by name)
const edges: Array<{
	source: string;
	target: string;
	relations: string[];
	description?: string;
	status?: string;
}> = [];
for (const conn of catalog.connections) {
	for (const src of asArray(conn.source)) {
		for (const tgt of asArray(conn.target)) {
			const sourceName = productsById.get(src)?.name;
			const targetName = productsById.get(tgt)?.name;
			if (!sourceName || !targetName || sourceName === targetName) continue;
			edges.push({
				source: sourceName,
				target: targetName,
				relations: conn.relations ?? [],
				description: conn.description,
				status: conn.status,
			});
		}
	}
}

const garden = {
	name: "Omniverse",
	description: "The complete Omni product ecosystem",
	icon: "🌱",
	subgardens,
	edges,
};

const file = `/**
 * Omniverse garden, generated from the catalog SSOT (\`_meta/catalog.json\`).
 *
 * AUTO-GENERATED by src/scripts/generateGarden.ts. Do not edit by hand.
 * Refresh with \`bun run src/scripts/generateGarden.ts\` from the metarepo.
 */

import type { GardenSchema } from "@omnidotdev/garden";

export const omniGarden = ${JSON.stringify(garden, null, 2)} as GardenSchema;
`;

await Bun.write(outPath, file);

// biome-ignore lint/suspicious/noConsole: build script output
console.info(
	`[garden] Wrote ${subgardens.length} realms, ${catalog.products.length} products, ${edges.length} edges`,
);
