/**
 * Omniverse garden, generated from the catalog SSOT (`_meta/catalog.json`).
 *
 * AUTO-GENERATED by src/scripts/generateGarden.ts. Do not edit by hand.
 * Refresh with `bun run src/scripts/generateGarden.ts` from the metarepo.
 */

import type { GardenSchema } from "@omnidotdev/garden";

export const omniGarden = {
  "name": "Omniverse",
  "description": "The complete Omni product ecosystem",
  "icon": "🌱",
  "subgardens": [
    {
      "name": "CORE",
      "description": "Unified business operations - Omni's unified business operations suite. Project management, CRM, finance, commerce, and everything businesses need to operate.",
      "icon": "☄️",
      "supergardens": [
        {
          "name": "Omniverse"
        }
      ],
      "sprouts": [
        {
          "name": "Runa",
          "homepage_url": "https://runa.omni.dev",
          "description": "A streamlined project management tool with agile workflows such as kanban.",
          "logo": "🌙",
          "tagline": "Lunar plans, stellar execution",
          "license": "Apache-2.0",
          "release_date": "2025-12-21",
          "self_hostable": true,
          "docs_url": "https://docs.omni.dev/core/runa"
        },
        {
          "name": "Backfeed",
          "homepage_url": "https://backfeed.omni.dev",
          "description": "A user feedback reporting platform that aggregates user data for your products, services, and experiences, providing a centralized location to iterate on your projects with user-driven insights.",
          "logo": "📣",
          "tagline": "Streamlined user feedback",
          "license": "Apache-2.0",
          "release_date": "2025-05-06",
          "self_hostable": true,
          "docs_url": "https://docs.omni.dev/core/backfeed"
        }
      ]
    },
    {
      "name": "ARMORY",
      "description": "Developer tools - Developer tools and utilities. Everything engineers need to build, test, deploy, and maintain software.",
      "icon": "🛠️",
      "supergardens": [
        {
          "name": "Omniverse"
        }
      ],
      "sprouts": [
        {
          "name": "Eden",
          "homepage_url": "https://eden.omni.dev",
          "description": "A Rust-powered CLI tool designed for developer onboarding that verifies required dependencies and configurations are properly installed before development begins.",
          "logo": "🌿",
          "tagline": "In the beginning, there were dependencies",
          "license": "Apache-2.0",
          "release_date": "2026-01-01",
          "self_hostable": false,
          "docs_url": "https://docs.omni.dev/armory/eden"
        }
      ]
    },
    {
      "name": "CODEX",
      "description": "Specifications and standards - Specifications, standards, and schemas. The protocols and formats that define how Omni systems communicate and interoperate.",
      "icon": "📜",
      "supergardens": [
        {
          "name": "Omniverse"
        }
      ],
      "sprouts": [
        {
          "name": "Garden",
          "homepage_url": "https://garden.omni.dev",
          "description": "A specification, backed by JSON Schema, for modeling ecosystems of products, services, and any other relational collections. A React-based visualization component is provided that enables you to create interactive, hierarchical diagrams of your ecosystem.",
          "logo": "🌱",
          "tagline": "Ecosystem visualization and modeling",
          "license": "Apache-2.0",
          "release_date": "2025-06-20",
          "self_hostable": false,
          "docs_url": "https://docs.omni.dev/codex/garden"
        },
        {
          "name": "life.json",
          "homepage_url": "https://life.omni.dev",
          "description": "A portable digital identity specification that allows you to own and control your personal data across platforms and services.",
          "logo": "🧬",
          "tagline": "Portable digital identity specification",
          "license": "Apache-2.0",
          "release_date": "2026-02-06",
          "self_hostable": false,
          "docs_url": "https://docs.omni.dev/codex/life-json"
        },
        {
          "name": "persona.json",
          "homepage_url": "https://persona.omni.dev",
          "description": "A portable digital identity specification for non-humans—AI assistants, brands, bots, mascots, and other non-human identities. Complements life.json (human identity) with non-human identity.",
          "logo": "🎭",
          "tagline": "Portable non-human identity specification",
          "license": "Apache-2.0",
          "release_date": "2026-02-06",
          "self_hostable": false,
          "docs_url": "https://docs.omni.dev/codex/persona-json"
        }
      ]
    },
    {
      "name": "REALITY",
      "description": "Spatial computing and XR - Omni's spatial computing realm focused on AR, XR, and real-world interfaces. Open, web-first tools for anchoring digital experiences to physical space.",
      "icon": "ᯅ",
      "supergardens": [
        {
          "name": "Omniverse"
        }
      ],
      "sprouts": [
        {
          "name": "RDK",
          "homepage_url": "",
          "description": "A React-first framework for building web-based XR experiences, from AR to VR, orchestrated through one unified API powered by Three.js and react-three-fiber.",
          "logo": "⊗",
          "tagline": "React-first XR development kit",
          "license": "Apache-2.0",
          "release_date": "2025-10-31",
          "self_hostable": false,
          "docs_url": "https://docs.omni.dev/reality/rdk"
        }
      ]
    }
  ],
  "edges": [
    {
      "source": "Runa",
      "target": "Backfeed",
      "relations": [
        "integrates",
        "consumes"
      ],
      "description": "Runa integrates Backfeed for user feedback on projects. Feedback items can be converted to Runa tasks, and task completion can trigger feedback status updates.",
      "status": "planned"
    },
    {
      "source": "persona.json",
      "target": "life.json",
      "relations": [
        "extends"
      ],
      "description": "persona.json complements life.json as twin specifications for identity duality. life.json defines human identity (user-owned), while persona.json defines non-human identity (developer-owned). They meet in the middle via life.json's assistants slice, which stores the user's relationship with each persona.",
      "status": "implemented"
    }
  ]
} as GardenSchema;
